import { describe, it } from "node:test";
import assert from "node:assert";
import {
	stripAiTells,
	humanizeCourseTitle,
	humanizeDescription,
	humanizeSectionTitle,
	humanizeVideoTitle,
	humanizeLessonIntro,
	generateQuiz,
	instructorPersona,
	humanizeCourse,
} from "../src/edu/humanize.mjs";

describe("humanize.mjs", () => {
	it("strips agentic-origin tells from text", () => {
		const input =
			"This course was generated by an AI agent swarm. Autonomous pipeline wrote the script. Director agent chose the topic.";
		const out = stripAiTells(input);
		assert.ok(!/agent|swarm|autonomous|generated by/i.test(out));
		assert.ok(out.length > 0);
	});

	it("strips AI-model tells", () => {
		const out = stripAiTells("As an AI, I recommend reading the docs. Language models excel at drafting.");
		assert.ok(!/AI|language model/i.test(out));
	});

	it("title-cases and cleans course titles", () => {
		assert.strictEqual(humanizeCourseTitle("prep tests for the aws sa exam"), "Prep Tests for the Aws Sa Exam");
		assert.strictEqual(humanizeCourseTitle(""), "Hands-On Practice Course");
	});

	it("falls back to a human-written description when input is too short", () => {
		const desc = humanizeDescription("short", { seed: 1 });
		assert.ok(desc.length > 100);
		assert.ok(!/agent|swarm|autonomous/i.test(desc));
	});

	it("keeps long human descriptions intact", () => {
		const long =
			"A thorough, step-by-step guide covering core concepts, worked examples, and hands-on exercises designed to build real confidence. Each section ends with a short self-check so you can confirm what stuck before moving on.";
		assert.strictEqual(humanizeDescription(long, { seed: 2 }), long);
	});

	it("generates natural section titles", () => {
		assert.strictEqual(humanizeSectionTitle(1, null), "Getting Started");
		assert.strictEqual(humanizeSectionTitle(2, null), "Core Concepts, Explained Simply");
		assert.strictEqual(humanizeSectionTitle(1, "intro to dns"), "Intro to Dns");
	});

	it("produces natural video titles, not 'Video lesson'", () => {
		const title = humanizeVideoTitle("video lesson", 3);
		assert.ok(!/video lesson/i.test(title));
		assert.ok(title.length > 0);
	});

	it("lesson intros are first-person and non-robotic", () => {
		const intro = humanizeLessonIntro(1, "Docker");
		assert.ok(intro.length > 40);
		assert.ok(!/module \d/i.test(intro));
	});

	it("quiz questions read like a human wrote them", () => {
		const quiz = generateQuiz(1, "Docker");
		assert.strictEqual(quiz.length, 3);
		for (const q of quiz) {
			assert.ok(!/Module \d: key concept|Concept A|Example 1|Pitfall 1/i.test(q.prompt + q.options.join(" ")));
			assert.ok(q.options.length >= 3);
			assert.ok(typeof q.correct_index === "number" && q.correct_index >= 0);
		}
	});

	it("instructor persona is a named human, no agent origin", () => {
		const p = instructorPersona({ env: {} });
		assert.ok(p.name.length > 0);
		assert.ok(p.title.length > 0);
		assert.ok(p.bio.length > 0);
		assert.ok(!/agent|swarm|autonomous|AI/i.test(`${p.name} ${p.title} ${p.bio}`));
	});

	it("humanizeCourse rewrites title, description and modules end-to-end", () => {
		const h = humanizeCourse({
			title: "Course created by the agentic swarm",
			description: "short",
			modules: [{ title: "Module 1", topic: "Docker", videoId: "v1" }],
			seed: 5,
		});
		assert.ok(!/agent|swarm|autonomous/i.test(h.title + h.description));
		assert.ok(h.description.includes("Led by"));
		assert.ok(h.modules[0].quiz.length === 3);
		assert.ok(h.modules[0].title.length > 0);
	});
});
