import { describe, it } from "node:test";
import assert from "node:assert";
import { LearnWorldsPublisher, generateQuiz, buildInteractivePointers } from "../src/edu/learnworlds-publisher.mjs";

function mockClient() {
	const calls = [];
	return {
		calls,
		async createCourse({ title, description, instructor }) {
			calls.push({ op: "createCourse", title, description, instructor });
			return { id: "course-1", title };
		},
		async createSection(courseId, { title }) {
			calls.push({ op: "createSection", courseId, title });
			return { id: `section-${calls.length}` };
		},
		async addVideoUnit(courseId, sectionId, opts) {
			calls.push({ op: "addVideoUnit", courseId, sectionId, opts });
			return { ok: true };
		},
		async addQuizUnit(courseId, sectionId, opts) {
			calls.push({ op: "addQuizUnit", courseId, sectionId, opts });
			return { ok: true };
		},
		async addInteractivePointer(courseId, sectionId, opts) {
			calls.push({ op: "addInteractivePointer", courseId, sectionId, opts });
			return { ok: true };
		},
		async setCoursePrice(courseId, priceCents) {
			calls.push({ op: "setCoursePrice", courseId, priceCents });
			return { ok: true };
		},
		async publishCourse(courseId) {
			calls.push({ op: "publishCourse", courseId });
			return { ok: true };
		},
	};
}

function makePublisher(m, extra = {}) {
	return new LearnWorldsPublisher({
		client: m,
		live: true,
		ownerDirective: () => true,
		priceMinCents: 500,
		priceMaxCents: 5000,
		...extra,
	});
}

describe("LearnWorldsPublisher", () => {
	it("parses interactive video timestamps from a script", () => {
		const pointers = buildInteractivePointers("at 0:12 key insight here. at 1:30 next marker.");
		assert.deepStrictEqual(pointers, [
			{ timestamp: "0:12", text: "key insight here" },
			{ timestamp: "1:30", text: "next marker" },
		]);
	});

	it("generates natural, human-sounding quiz questions per module", () => {
		const quiz = generateQuiz(1, "Fractions");
		assert.strictEqual(quiz.length, 3);
		assert.ok(!/Module \d:/.test(quiz[0].prompt), "no templated module prompts");
		assert.ok(quiz[0].prompt.includes("Fractions"));
		assert.ok(quiz[0].options.length >= 3);
		assert.ok(quiz.every((q) => q.prompt.endsWith("?") || q.prompt.includes("?")));
	});

	it("publishes a course with sections, video, pointers, quiz, and price clamp", async () => {
		const m = mockClient();
		const publisher = makePublisher(m);
		const result = await publisher.publishCourse({
			title: "Prep tests for the aws sa exam",
			priceCents: 100,
			modules: [{ title: "Module 1", videoId: "v1", script: "at 0:12 intro" }],
		});
		assert.strictEqual(result.courseId, "course-1");
		assert.strictEqual(result.priceCents, 500);
		assert.strictEqual(result.publishedModules.length, 1);
		const ops = m.calls.map((c) => c.op);
		assert.ok(ops.includes("createSection"));
		assert.ok(ops.includes("addVideoUnit"));
		assert.ok(ops.includes("addQuizUnit"));
		assert.ok(ops.includes("addInteractivePointer"));
		const courseCall = m.calls.find((c) => c.op === "createCourse");
		assert.strictEqual(courseCall.title, "Prep Tests for the Aws Sa Exam");
		assert.ok(courseCall.description.length > 80);
	});

	it("humanizes by default so the school shows no agentic-origin tells", async () => {
		const m = mockClient();
		const publisher = makePublisher(m);
		await publisher.publishCourse({
			title: "Course generated by an AI agent swarm for IT pros",
			description: "Created by the autonomous agent pipeline. A practical walkthrough.",
			modules: [{ title: "Module 1", videoId: "v1" }],
		});
		const courseCall = m.calls.find((c) => c.op === "createCourse");
		assert.ok(!/generated by an? AI|agent swarm|autonomous/i.test(courseCall.title));
		assert.ok(!/agent|swarm|autonomous/i.test(courseCall.description));
		assert.strictEqual(courseCall.instructor.name.length > 0, true);
		assert.ok(courseCall.instructor.bio.length > 0);
	});

	it("auto-publishes when LEARNWORLDS_PUBLISH is set", async () => {
		process.env.LEARNWORLDS_PUBLISH = "true";
		const m = mockClient();
		const publisher = makePublisher(m);
		const result = await publisher.publishCourse({ title: "T", modules: [] });
		assert.strictEqual(result.status, "published");
		assert.ok(m.calls.some((c) => c.op === "publishCourse"));
		delete process.env.LEARNWORLDS_PUBLISH;
	});

	it("refuses to publish without SWARM_LIVE=true", async () => {
		const m = mockClient();
		const publisher = new LearnWorldsPublisher({ client: m, ownerDirective: () => true });
		process.env.OWNER_PAYPAL_EMAIL = "owner@example.com";
		await assert.rejects(
			() => publisher.publishCourse({ title: "T", modules: [], payoutDestination: { beneficiary: "owner@example.com", type: "email" } }),
			/SWARM_LIVE/,
		);
	});

	it("rejects when payout is not the pre-set owner account", async () => {
		const m = mockClient();
		const publisher = makePublisher(m, { ownerDirective: undefined });
		process.env.OWNER_PAYPAL_EMAIL = "owner@example.com";
		await assert.rejects(
			() => publisher.publishCourse({ title: "T", modules: [], payoutDestination: { beneficiary: "other@example.com", type: "email" } }),
			/OwnerDirectiveViolation/,
		);
	});

	it("allows payout to the pre-set owner account", async () => {
		const m = mockClient();
		const publisher = makePublisher(m, { ownerDirective: undefined });
		process.env.OWNER_PAYPAL_EMAIL = "owner@example.com";
		const result = await publisher.publishCourse({
			title: "T",
			modules: [],
			payoutDestination: { beneficiary: "owner@example.com", type: "email" },
		});
		assert.strictEqual(result.courseId, "course-1");
	});

	it("dynamic price clamps to allowed range", async () => {
		const m = mockClient();
		const publisher = makePublisher(m, { priceMaxCents: 1000 });
		const price = await publisher.dynamicPrice({ courseId: "c1", basePriceCents: 300, demandFactor: 5 });
		assert.strictEqual(price, 1000);
	});

	it("publishAll dedupes repeated titles", async () => {
		const m = mockClient();
		const publisher = makePublisher(m);
		const courses = [{ title: "Same" }, { title: "Same" }];
		const results = await publisher.publishAll({ courses, payoutDestination: {} });
		assert.strictEqual(results.length, 1);
	});
});
