import { describe, it } from "node:test";
import assert from "node:assert";
import SiteStandardsAuditor, { auditStandards, mainSiteDefaults } from "../src/edu/site-standards.mjs";

const COMPLIANT = {
	target: "https://www.realworldcerts.com",
	metaTitle: "Cybersecurity Certification Prep Course",
	metaDescription: "Structured practice for the CompTIA Security+ exam covering all six domains with hands-on questions.",
	priceCents: 4900,
	https: true,
	refundPolicy: true,
	supportPage: "/support",
	mobileResponsive: true,
	primaryCta: "Start the course",
	copy: "Practical practice questions written by a working instructor.",
	affiliateProgram: true,
	affiliateCommissionRate: 0.2,
	examCodes: "SY0-701",
	objectives: "Six domains of Security+",
	testimonials: "Over 200 students rated this prep 4.8/5.",
	productNames: ["Security+ Practice Exams"],
	salesMapping: true,
};

describe("site-standards.mjs", () => {
	it("grades a fully compliant profile A", () => {
		const report = auditStandards({ profile: COMPLIANT });
		assert.ok(report.grade === "A");
		assert.ok(report.verdict === "up_to_standards");
		assert.ok(report.failCount === 0);
	});

	it("flags gaps in a sparse profile", () => {
		const report = auditStandards({ profile: { priceCents: 0, https: false } });
		assert.ok(report.verdict === "needs_attention");
		assert.ok(report.failing.includes("seo_title"));
		assert.ok(report.failing.includes("pricing"));
		assert.ok(report.failing.includes("trust"));
	});

	it("detects AI tells in copy as human_copy failure", () => {
		const report = auditStandards({
			profile: { ...COMPLIANT, copy: "This course was generated by an AI pipeline." },
		});
		assert.ok(report.failing.includes("human_copy"));
	});

	it("counts a populated meta title as passing seo", () => {
		const report = auditStandards({ profile: { metaTitle: "A sufficiently long unique title" } });
		const seo = report.checks.find((c) => c.id === "seo_title");
		assert.ok(seo.status === "pass");
	});

	it("maps live sales rows to product names", () => {
		const report = auditStandards({
			profile: { salesMapping: false },
			liveSales: [{ productName: "Security+ Practice Exams" }, { productName: "A+" }],
		});
		const sales = report.checks.find((c) => c.id === "sales_mapping");
		assert.ok(sales.status === "pass");
	});

	it("mainSiteDefaults sets trust baseline for realworldcerts", () => {
		const d = mainSiteDefaults();
		assert.ok(d.https === true);
		assert.ok(d.refundPolicy === true);
		assert.ok(d.affiliateProgram === true);
	});

	it("audit() returns preview in dry-run", async () => {
		const auditor = new SiteStandardsAuditor({ live: true });
		const out = await auditor.audit({ profile: COMPLIANT, dryRun: true });
		assert.ok(out.status === "standards_audit_preview");
		assert.ok(out.audit.grade === "A");
	});

	it("audit() refuses live mode without SWARM_LIVE", async () => {
		const auditor = new SiteStandardsAuditor();
		await assert.rejects(() => auditor.audit({ profile: COMPLIANT, dryRun: false }), /SWARM_LIVE/);
	});
});
