#Requires -Version 5
<#
.SYNOPSIS
  Enables / disables the git hook extensions (pre-commit settlements probe,
  post-commit auto-push) by copying scripts to the worktree's hooks dir.

.DESCRIPTION
  Two install modes per hook:
    - Enable  : copies script to GIT_DIR/hooks/<hook> (no extension) and
                does chmod +x on POSIX; on Windows adds PATHEXT-dot-pwsh
                bootstrap so git-for-windows invokes it.
    - Disable : removes the installed hook file (restores .sample)

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File scripts\git-extensions\install-hooks.ps1 -Enable pre-commit
  powershell -ExecutionPolicy Bypass -File scripts\git-extensions\install-hooks.ps1 -Enable post-commit
  powershell -ExecutionPolicy Bypass -File scripts\git-extensions\install-hooks.ps1 -DisableAll
  powershell -ExecutionPolicy Bypass -File scripts\git-extensions\install-hooks.ps1 -Status
#>

[CmdletBinding()]
param(
  [ValidateSet('pre-commit','post-commit')]
  [string]$Enable,
  [ValidateSet('pre-commit','post-commit')]
  [string]$Disable,
  [switch]$DisableAll,
  [switch]$Status
)

$ErrorActionPreference = 'Stop'

$git = if (Test-Path -LiteralPath (Join-Path $env:ProgramFiles 'Git\bin\git.exe')) { (Join-Path $env:ProgramFiles 'Git\bin\git.exe') } else { 'git.exe' }
$ws = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
& $git --no-pager --no-optional-locks -C $ws rev-parse --git-dir >$null 2>&1 | Out-Null
$gitDir = (& $git --no-pager --no-optional-locks -C $ws rev-parse --git-dir 2>$null).Trim()
# worktree: $gitDir is the worktree work-specific dir; hooks are shared at the
# common .git/hooks of the base repo (worktrees share hooks unless overridden)
$hooksDir = if (Test-Path -LiteralPath (Join-Path $gitDir 'hooks')) { (Join-Path $gitDir 'hooks') }
            elseif (Test-Path -LiteralPath (Join-Path (Split-Path -Parent $gitDir) 'hooks')) { (Join-Path (Split-Path -Parent $gitDir) 'hooks') }
            else { (Join-Path $gitDir 'hooks') }

if (-not (Test-Path -LiteralPath $hooksDir)) { New-Item -ItemType Directory -Path $hooksDir -Force | Out-Null }

$map = @{
  'pre-commit'  = @{ Src = Join-Path $PSScriptRoot 'pre-commit.settlements-dryrun.ps1' }
  'post-commit' = @{ Src = Join-Path $PSScriptRoot 'post-commit.auto-push-https-origin.ps1' }
}

function Get-InstallStatus($hook) {
  $target = Join-Path $hooksDir $hook
  if (Test-Path -LiteralPath $target) { 'INSTALLED' } else { 'NOT INSTALLED (sample only)' }
}

if ($Status) {
  Write-Host "GIT_DIR     = $gitDir"
  Write-Host "HOOKS_DIR   = $hooksDir"
  Write-Host "WORKTREE    = $ws"
  Write-Host ""
  foreach ($h in $map.Keys) { Write-Host ("  {0,-14}  {1}" -f $h,(Get-InstallStatus $h)) }
  exit 0
}

if ($DisableAll) { foreach ($h in @('pre-commit','post-commit')) {
  $t = Join-Path $hooksDir $h
  if (Test-Path -LiteralPath $t) { Remove-Item -LiteralPath $t -Force -ErrorAction Stop; Write-Host "DISABLED $h -> removed $t" }
  else { Write-Host "DISABLED $h -> already not installed" }
} exit 0 }

if ($Enable) {
  $src = $map[$Enable].Src; $target = Join-Path $hooksDir $Enable
  Copy-Item -LiteralPath $src -Destination ($target + '.ps1') -Force
  # git-for-windows needs a PATHEXT-less wrapper that calls pwsh
  $wrapper = @(
    '#!/bin/sh',
    '# AUTO-GENERATED by scripts/git-extensions/install-hooks.ps1',
    "pwsh -NoProfile -ExecutionPolicy Bypass -File `"`$(dirname `"`$0`")/$Enable.ps1`" `"`$@`"",
    'exit $?'
  ) -join "`n"
  [System.IO.File]::WriteAllText($target, $wrapper, [System.Text.UTF8Encoding]::new($false))
  Write-Host "ENABLED  $Enable  -> $target"
  exit 0
}
if ($Disable) {
  $t1 = Join-Path $hooksDir $Disable
  $t2 = $t1 + '.ps1'
  if (Test-Path -LiteralPath $t1) { Remove-Item $t1 -Force; Write-Host "removed $t1" }
  if (Test-Path -LiteralPath $t2) { Remove-Item $t2 -Force; Write-Host "removed $t2" }
  Write-Host "DISABLED $Disable"
  exit 0
}
