name: Deploy Static Site to GitHub Pages
on:
  workflow_dispatch:
permissions:
  pages: write
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Upload static artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: catalogue
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
